### ISSUE TITLE
pic can not appear on website (relative path issue)

### ISSUE THREAD

**Issue by JimmyDingyiming** [hupili/datavis.studio#11]
<img width="289" alt="2019-03-02 10 11 27" src="https://user-images.githubusercontent.com/47048572/53683459-ea9c7e00-3d3b-11e9-81a1-689ecd772976.png">
<img width="57" alt="2019-03-02 10 14 55" src="https://user-images.githubusercontent.com/47048572/53683462-ec664180-3d3b-11e9-89eb-01859a2fed36.png">
I am trying to embed the pic into the website, can anyone tell me what is the problem here?

**Comment by hupili** [comment]
@JimmyDingyiming , can you bring up following information?

* Operating system:
* IDE (e.g. VSCode):
* Browser (Chrome/ Safari/ Firefox/ VSCode Embedded):
* Internet access (Location/ Type):
* The link to your issue pages hosted on gh-pages (`xxx.github.io/page.html`):
* The link to your repo (`github.com/user/repo`):

Also, please open Chrome Developer Console, and let us know the error message.

**Comment by hupili** [comment]
@JimmyDingyiming , please also refer to other issue posts, e.g. https://github.com/hupili/datavis.studio/issues/5 . Once, we get the context, we can quickly check the issue. Please try to push the intermediate version to GitHub Pages. If you worry the intermediate version does not look good on your homepage, you can use a subpath, e.g. `test/index.html`. We can visit that accordingly.

**Comment by hupili** [comment]
https://jimmydingyiming.github.io/?11

**Comment by hupili** [comment]
This is what we see from the current online version:

<img width="995" alt="screenshot 2019-03-04 at 4 04 28 pm" src="https://user-images.githubusercontent.com/1227160/53718856-5e9f6900-3e97-11e9-908a-4f1b77c34796.png">

Right click the links and open in new tab. Then we find 404:

<img width="577" alt="screenshot 2019-03-04 at 4 04 46 pm" src="https://user-images.githubusercontent.com/1227160/53718885-6fe87580-3e97-11e9-86e8-5be348ae12b8.png">

That means, there are no such files like `images/Jimmy%20travel.%20JPG` on gh-pages server.

We checkout the GitHub repo: https://github.com/jimmydingyiming/jimmydingyiming.github.io

[current version](https://github.com/JimmyDingyiming/JimmyDingyiming.github.io/tree/303723eb499f3cdeb9ee4861) does not include those expected files in `images/*`.

<img width="1032" alt="screenshot 2019-03-04 at 4 08 01 pm" src="https://user-images.githubusercontent.com/1227160/53718966-b342e400-3e97-11e9-8cac-246370ae5ddf.png">

**Comment by hupili** [comment]
So the solution is to:

1. Check if you have `images/*` in your local disk
2. If above is alright, check if you have committed those files using GitHub Desktop.

**Comment by hupili** [comment]
@JimmyDingyiming , btw, I see some `<<<<< HEAD` type of text from you page. That may arise from "merge conflict", usually after you modify the repo on different machines without properly sync. Please checkout this post to see if you can resolve those texts yourself: https://stackoverflow.com/questions/7901864/git-conflict-markers .
