### ISSUE TITLE
The element is not flexible  with the browse shaping.

### ISSUE THREAD

**Issue by Ly-Iris** [hupili/datavis.studio#13]
# Troubleshooting

## Describe your environment

* IDE (e.g. VSCode):VSCode
* Browser (Chrome/ Safari/ Firefox/ VSCode Embedded):Chrome
* The link to your issue pages hosted on gh-pages (`xxx.github.io/page.html`): Ly-Iris.github.io/hw2/

## Describe your question

I used the (div class="card") and (div class="avatar") function in my code, but when I shape my browser, the elements "card" and "avatar" do not move together.

## Describe the efforts you have spent on this issue

I have searched online and viewed many videos.

### Have you Google or StackOverflow?

Yes.

### Do they solve or partially solve your question?

No.

### What is the closest answer you can find?

It is suggested that I should use the @media function, but I don't think it's related to this tag.

**Comment by hupili** [comment]
Ly-Iris.github.io/hw2/

**Comment by hupili** [comment]
http://Ly-Iris.github.io/hw2/

**Comment by hupili** [comment]
Short take is that you usually do not use margin/ padding to *layout* objects.

Current:

<img width="978" alt="screenshot 2019-03-08 at 2 21 48 pm" src="https://user-images.githubusercontent.com/1227160/54011520-d1695680-41ad-11e9-8eaf-ce5fdbdb12d4.png">

Use `position: absolute` and place the element w.r.t. its parent:

<img width="1015" alt="screenshot 2019-03-08 at 2 23 07 pm" src="https://user-images.githubusercontent.com/1227160/54011545-e80fad80-41ad-11e9-9f85-e6e3669a7d19.png">

effect of sizing:

<img width="599" alt="screenshot 2019-03-08 at 2 23 19 pm" src="https://user-images.githubusercontent.com/1227160/54011572-f78ef680-41ad-11e9-94fc-9abe2b091fdc.png">

There are other details that we can discuss f2f.

**Comment by Ly-Iris** [comment]
### Conclusions

1. It's about the "margin" and "position" issue. You can compare the codes before and after to realize and have a try.
2. The picture does not display because my path is wrong.

### This is the first version:
         `body {
	            background-image: url('../images/wallhaven-688773.jpg');
                    background-repeat: no-repeat;
	            background-position: 100% center;
	            background-size: cover;
          }
            .card {
                    background: #FFFFFF;
                    min-height: 850px;
                    max-width: 800px;
                    min-width: 400px;
                    margin:_ 300px;
                    border-radius: 3%;
                    box-shadow: 0 30px 30px 0 rgba(0, 0, 0, 0.50);
        }
        
        #avatar {
            background-image:_ url('../images/IMG_0438.png');
            background-size: contain;
            margin: -80px 10px 8px 550px;
            display: inline-block;
            height: 200px;
            width: 200px;
            border: 3px solid rgba(32, 220, 226, 0.5);
            border-radius: 50%;
            background-repeat: no-repeat;
            position:_ relative;
        }`

### This is the corrected version:
          `body {
                    background-image: url('images/wallhaven-688773.jpg');
                    background-repeat: no-repeat;
	            background-position: 100% center;
	            background-size: cover;
          }
            .card {
	            background: #FFFFFF;
                    min-height: 850px;
                    max-width: 800px;
                    min-width: 400px;
                    margin-left: auto;
	            margin-right: auto;
	            margin-top: 50px;
                    border-radius: 3%;
                    box-shadow: 0 30px 30px 0 rgba(0, 0, 0, 0.50);
                    position: relative;
	   }
              #avatar {
                    background-image: url('images/IMG_0438.png');
	            background-size: contain;
                    right: 100px;
	            top: -80px;
	            display: inline-block;
	            height: 200px;
	            width: 200px;
	            border: 3px solid rgba(32, 220, 226, 0.5);
	            border-radius: 50%;
	            background-repeat: no-repeat;
                    position: absolute;
	     }`

**Comment by hupili** [comment]
@Ly-Iris ! Let's conclude a few key points here:

* Spacing can be done by margin/ border/ padding/ innerHTML size. -- Use them according to the meaning, instead of according to how they appears on the browser screen (all could be blank-space).
* Center an element: margin-left auto; margin-right auto.
* `position: absolute` can be used to place an element out of regular "flow". "flow" means top-to-bottom and left-to-right.
* In order to make `position: absolute` work as expected, its parent element needs to be `relative`. Or it will recursively track back towards the root until one `relative` is found.
