### ISSUE TITLE
How to change capital letters for Mac

### ISSUE THREAD

**Issue by dragonmasterhk** [hupili/datavis.studio#18]
At first, I created two local folders with the names of "HW1" and "HW2" but the required names should be "hw1" and "hw2"; so I changed the local folders' names and pushed online. The thing is that nothing changed online. The names of the folders are still "HW1" and "HW2".

<img width="882" alt="Screen Shot 2019-03-09 at 11 09 43 AM" src="https://user-images.githubusercontent.com/47048552/54065879-958fc900-4261-11e9-9867-5026c1345c32.png">

<img width="1048" alt="Screen Shot 2019-03-09 at 11 12 50 AM" src="https://user-images.githubusercontent.com/47048552/54065793-6cbb0400-4260-11e9-9a65-067f89a8eea5.png">

Solution: backup the files inside. delete the old "HW1" and "HW2" folders and create"hw1" and "hw2". then paste the files into the new folders.

**Comment by hupili** [comment]
Key points:

* path on MAC system is [case insensitive but case preserving](https://apple.stackexchange.com/a/22304), so `hw1` and `HW1` appears as one thing in your local disk
* path in URL scheme is **case sensitive**, so `xxx.github.io/hw1` and `xxx.github.io/HW1` are two different locations.
