### ISSUE TITLE
Highmap incompatible with Highcharts

### ISSUE THREAD

**Issue by tiffanynys** [hupili/datavis.studio#32]
# Troubleshooting

## Describe your environment
(26/4) After adding the codes of Highcharts to the webpage, Highmap cannot be shown in [my group work](https://tiffanynys.github.io/final/). 

Error message
![Screenshot 2019-04-29 at 4 58 10 AM](https://user-images.githubusercontent.com/47048732/56870044-9f50d400-6a3b-11e9-9922-077660f418e4.png)

(28/4) While I tried to create two templates ([one with map only](https://tiffanynys.github.io/problem/maponly/) and [one with map and chart](https://tiffanynys.github.io/problem/mapnchart/), the map is compatible with the graph lol. I don't know why.

* Operating system: Mac
* IDE (e.g. VSCode): VSCode
* Browser (Chrome/ Safari/ Firefox/ VSCode Embedded): Chrome
* Internet access (Location/ Type): ??
* The link to your issue pages hosted on gh-pages (`xxx.github.io/page.html`): https://tiffanynys.github.io/final/, _for your reference: https://tiffanynys.github.io/problem/maponly/ & https://tiffanynys.github.io/problem/mapnchart/_
* The link to your repo (`github.com/user/repo`): https://github.com/tiffanynys/tiffanynys.github.io/blob/master/final/index.html, _for your reference: https://github.com/tiffanynys/tiffanynys.github.io/blob/master/problem/maponly/index.html & https://github.com/tiffanynys/tiffanynys.github.io/blob/master/problem/mapnchart/index.html_

**Comment by ivywze** [comment]
The issue might happen when highmap and highcharts are built with different versions. One easy and quick way to solve the problem will be to use `<iframe>` to insert charts to the main page that's already done.

**Comment by hupili** [comment]
@tiffanynys  any good news of the integration?   @ivyWANG958  can you find an example showing the iframe embedding trick?

**Comment by tiffanynys** [comment]
I change the  〈div> 〈/div> for the chart to <iframe></iframe>
An empty rectangular box appears with nth inside :-S

**Comment by ivywze** [comment]
Here is an [example](https://ivywang958.github.io/homework7/) of how to use `<iframe>`. You could see trick - how I insert the second chart to the main page.

**Comment by tiffanynys** [comment]
wow, thank you
problem fixed!
