### ISSUE TITLE
About the author-block 

### ISSUE THREAD

**Issue by Ly-Iris** [hupili/datavis.studio#5]
How to set the author-block so that it doesn't overlap my headline? Here is my page[ly-iris.github.io](url)

**Comment by hupili** [comment]
ly-iris.github.io

**Comment by hupili** [comment]
@Ly-Iris , at this stage there is no way to do so (i.e. with only HTML). We'll soon learn how to do it when we enter HTML/CSS section.

However, as a general tip: You need to be **flexible**. If you don't know how to modify the template yet, you can adapt your content accordingly. One way to "hack" this is: put your title text empty. Use your familiar graphics tool to put the title text onto the background image.

**Comment by hupili** [comment]
For the completeness of this issue and for future reference of random visitor, here is the way to modify font-size via CSS:

<img width="936" alt="screenshot 2019-02-15 at 10 12 19 pm" src="https://user-images.githubusercontent.com/1227160/52861958-ec2c4a80-316e-11e9-90a2-7f37da7f5334.png">

**Comment by Ly-Iris** [comment]
OK，get it.I’ll have a try. Thx！

HU, Pili <notifications@github.com>于2019年2月15日 周五22:12写道：
